### ISSUE TITLE
Rails Group Project

### ISSUE THREAD

**Issue by DyaryRaoof** [DyaryRaoof/recipes#9]
There are 2 people in this project.
Project link: https://github.com/DyaryRaoof/recipes
Member 1 is @DyaryRaoof 
Member 2 is @mustabbas

**Comment by rloterh** [comment]
Hi Team, 

You did extremely great on this task! 👏 👏 
There are however a few changes that you still need to work on to go to the next task/ project but you are almost there! 🚦   🚦  

## Good Points 👍  
- Fiar distribution of task

## Required Changes ♻️
- [ ] Some of the tasks on the boards do not have descriptions. Kindly ensure to provide a description for **all** tasks.
<br>
Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by emmanuellekamwa** [comment]
**STATUS: APPROVED 🍾🎉✔**
Hello @DyaryRaoof and @mustabbas 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
